const NEXT_PUBLIC_CHANNEL_URL = process.env.NEXT_PUBLIC_CHANNEL_URL ?? ''
const NEXT_PUBLIC_BASE_URL_API = process.env.NEXT_PUBLIC_BASE_URL_API ?? ''

export const ENVIRONMENT_VARIABLES = {
  NEXT_PUBLIC_CHANNEL_URL,
  NEXT_PUBLIC_BASE_URL_API,
}
